defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: example_development

test:
  <<: *defaults
  database: example_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: example_production